default_language_version:
  python: python3.8

default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --config-file pyproject.toml
        types_or: [python, pyi]
        language: system
        exclude: ^docs/.*
      - id: ruff
        name: ruff
        entry: ruff --config pyproject.toml --fix --exit-non-zero-on-fix
        types_or: [python, pyi]
        language: system
        exclude: ^docs/.*
        require_serial: true
      - id: isort
        name: isort
        entry: isort --settings-path pyproject.toml
        types_or: [python, pyi]
        language: system
      - id: black
        name: black
        entry: black --config pyproject.toml
        types_or: [python, pyi]
        language: system
      - id: commitizen
        name: commitizen
        entry: cz check --allow-abort --commit-msg-file
        stages: [commit-msg]
        language: system
      - id: pip-compile
        name: pip-compile
        entry: pip-compile --all-extras pyproject.toml
        files: ^pyproject.toml|requirements.txt$
        pass_filenames: false
        language: system
