name: Linting

on:
  workflow_call:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  spelling:
    name: "Spelling"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run spellcheck
      uses: rojopolis/spellcheck-github-actions@0.30.0
